<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMd5wilu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMd5wilu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMd5wilu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMd5wilu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMd5wilu\appProdProjectContainer([
    'container.build_hash' => 'Md5wilu',
    'container.build_id' => 'aa771d53',
    'container.build_time' => 1611158793,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMd5wilu');
